spring.application.name=backend
server.port=8080

# MongoDB Configuration
#spring.data.mongodb.uri=mongodb://localhost:27017/smart_campus
spring.data.mongodb.uri=mongodb+srv://Sarangan:saru123@cluster0.ctferfm.mongodb.net/smartcampus?retryWrites=true&w=majority
# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=1006850793257-8viof1farv3ml9ivftrom148lubbv17l.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/login/oauth2/code/google

# JWT Configuration
app.jwt.secret=mySecretKeyForJwtTokenGenerationSmartCampus2026PafAssignment
app.jwt.expiration-ms=86400000

# CORS
app.cors.allowed-origins=http://localhost:3000
